"""Generate shell scripts from sequential workflow patterns.

v0.3 feature — stub present, full implementation ships in v0.3.
"""

from __future__ import annotations

from pathlib import Path

from ai_habits.patterns.clustering import Pattern


def generate_script(
    pattern: Pattern,
    output_dir: Path | None = None,
) -> Path:
    """Generate a shell script draft for a sequential workflow pattern.

    Args:
        pattern: A repeatable-workflow pattern cluster.
        output_dir: Directory to write to (default: ./scripts/).

    Returns:
        Path of the written .sh file.
    """
    if output_dir is None:
        output_dir = Path.cwd() / "scripts"
    output_dir.mkdir(parents=True, exist_ok=True)

    slug = _to_slug(pattern.label or pattern.id)
    output_path = output_dir / f"{slug}.sh"

    content = _build_script(pattern)
    output_path.write_text(content, encoding="utf-8")
    output_path.chmod(0o755)
    return output_path


def _build_script(pattern: Pattern) -> str:
    label = pattern.label or f"Pattern {pattern.id}"
    samples = "\n".join(f"# - {t}" for t in pattern.sample_texts[:3])
    return f"""\
#!/usr/bin/env bash
# {label}
# Generated by ai-habits from pattern {pattern.id} ({pattern.size} occurrences)
#
# Evidence — sample conversations that triggered this pattern:
{samples}
#
# TODO: Replace the steps below with the actual commands from your workflow

set -euo pipefail

echo "Running: {label}"

# Step 1: TODO
# e.g. npm run lint

# Step 2: TODO
# e.g. npm test

# Step 3: TODO
# e.g. git add -p && git commit

echo "Done."
"""


def _to_slug(text: str) -> str:
    import re
    slug = text.lower().strip()
    slug = re.sub(r"[^a-z0-9\s-]", "", slug)
    slug = re.sub(r"\s+", "-", slug)
    return re.sub(r"-+", "-", slug)[:40].strip("-") or "workflow"
