"""Generate SKILL.md drafts from repeatable-workflow pattern clusters.

v0.3 feature — stub present, full implementation ships in v0.3.
"""

from __future__ import annotations

from pathlib import Path

from ai_habits.patterns.clustering import Pattern
from ai_habits.utils import llm


def generate_skill(
    pattern: Pattern,
    output_dir: Path | None = None,
) -> Path:
    """Generate a SKILL.md draft for *pattern*.

    Args:
        pattern: A classified pattern cluster.
        output_dir: Directory to write to (default: .claude/skills/<slug>/).

    Returns:
        Path of the written SKILL.md file.
    """
    if output_dir is None:
        slug = _to_slug(pattern.label or pattern.id)
        output_dir = Path.cwd() / ".claude" / "skills" / slug
    output_dir.mkdir(parents=True, exist_ok=True)
    output_path = output_dir / "SKILL.md"

    # Try LLM generation first
    content = llm.generate_skill_draft(
        pattern_summary=pattern.label or f"Pattern {pattern.id}",
        sample_messages=pattern.sample_texts,
    )

    if content is None:
        content = _fallback_skill(pattern)

    output_path.write_text(content, encoding="utf-8")
    return output_path


def _fallback_skill(pattern: Pattern) -> str:
    """Generate a basic skill template without LLM."""
    label = pattern.label or f"Pattern {pattern.id}"
    samples = "\n".join(f"- {t}" for t in pattern.sample_texts[:3])
    return f"""\
# {label}

<!-- Generated by ai-habits from pattern {pattern.id} ({pattern.size} occurrences) -->
<!-- Occurred {pattern.size} times between {pattern.first_seen} and {pattern.last_seen} -->

## Description

<!-- TODO: Describe what this skill does -->
{label}

## Usage

<!-- TODO: Describe how to invoke this skill -->
/skill {_to_slug(label)}

## Context

<!-- TODO: Fill in the key context Claude needs every time this is invoked -->
<!-- Evidence — sample messages that triggered this pattern: -->
{samples}

<!-- Add the actual instructions here -->
"""


def _to_slug(text: str) -> str:
    import re
    slug = text.lower().strip()
    slug = re.sub(r"[^a-z0-9\s-]", "", slug)
    slug = re.sub(r"\s+", "-", slug)
    return re.sub(r"-+", "-", slug)[:40].strip("-") or "skill"
